version: "3.5"

services:
  nginx:
    container_name: nginx
    image: nginx
    ports: 
      - 80:80
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/public_html
    depends_on:
      - php
      - mysql

  php:
    container_name: php
    build: ./images/php
    volumes:
      - ./www:/var/www/public_html
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: testdb
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootroot
    depends_on:
      - php
      - mysql
